kind: pipeline
name: default

steps:
  - name: test
    image: python:3.6
    environment:
      ROBERTO_CONDA_BASE_PATH: '${HOME}/cache/miniconda3'
      CONDA_BLD_PATH: '${HOME}/conda-bld'
      # Tell roberto which branch is being merged into, in case of a PR.
      # TODO Not sure if this is going to work
      ROBERTO_MERGE_BRANCH: '${DRONE_BRANCH}'
      # No deployment at the moment
      ROBERTO_DEPLOY_BINARY: 0
      ROBERTO_DEPLOY_NOARCH: 0
      TWINE_USERNAME: theochem
    commands:
      - python3 -m pip install . coverage --user
      - python3 -m coverage run --branch --source=roberto -m roberto robot
      # Report and upload also the additional coverage.
      - python3 -m coverage report -m
      - python3 -m coverage xml -i -o coverage_run.xml
      - bash <(curl -s https://codecov.io/bash)
