jobs:
  - job: 'Linux'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        py36:
          ROBERTO_CONDA_PINNING: python 3.6
        py37:
          ROBERTO_CONDA_PINNING: python 3.7
      maxParallel: 2

    steps:
      - bash: echo "##vso[task.prependpath]${CONDA}/bin"
        displayName: Add conda to PATH

      - bash: sudo chown -R $USER ${CONDA}
        displayName: Take ownership of conda installation

      - bash: |
          conda activate base
          python --version
          export ROBERTO_CONDA_BASE_PATH=${CONDA}
          export CONDA_BLD_PATH=${HOME}/conda-bld
          conda install setuptools coverage pip
          pip install .
          coverage run --branch --source=roberto -m roberto robot
          coverage report -m
          coverage xml -i -o coverage_run.xml
        displayName: 'Install and test package'
        Arguments: -x

  - job: 'MacOSX'
    pool:
      vmImage: 'macOS-10.13'
    strategy:
      matrix:
        py36:
          ROBERTO_CONDA_PINNING: python 3.6
        py37:
          ROBERTO_CONDA_PINNING: python 3.7
      maxParallel: 2

    steps:
      - bash: echo "##vso[task.prependpath]${CONDA}/bin"
        displayName: Add conda to PATH

      - bash: sudo chown -R $USER ${CONDA}
        displayName: Take ownership of conda installation

      - bash: |
          conda activate base
          python --version
          export ROBERTO_CONDA_BASE_PATH=${CONDA}
          export CONDA_BLD_PATH=${HOME}/conda-bld
          conda install setuptools coverage pip
          pip install .
          coverage run --branch --source=roberto -m roberto robot
          coverage report -m
          coverage xml -i -o coverage_run.xml
        displayName: 'Install and test package'
        Arguments: -x
