package:
  version: "{{ PROJECT_VERSION }}"
  name: 'roberto'

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"
  entry_points:
    - rob = roberto.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.7
    - pyyaml
    - invoke

test:
  requires:
    - python
    - pytest
    - pytest-xdist
  imports:
    - roberto
  commands:
    - pytest -v --pyargs roberto -n auto

about:
  dev_url: https://github.com/theochem/roberto
  description: Collection of configurable development workflows
  license: GPL-3.0
  license_family: GPL
  home: https://theochem.github.io/roberto/
  license_file: LICENSE.txt
  doc_url: https://theochem.github.io/roberto/
